# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_27_4/Linux64bit+3.10-2.17/bin/cmake

# The command to remove a file.
RM = /cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_27_4/Linux64bit+3.10-2.17/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /exp/sbnd/app/users/npando/BuildEventGenerators/HepMC3Analysis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /exp/sbnd/app/users/npando/BuildEventGenerators/HepMC3Analysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_27_4/Linux64bit+3.10-2.17/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_27_4/Linux64bit+3.10-2.17/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /exp/sbnd/app/users/npando/BuildEventGenerators/HepMC3Analysis/CMakeFiles /exp/sbnd/app/users/npando/BuildEventGenerators/HepMC3Analysis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /exp/sbnd/app/users/npando/BuildEventGenerators/HepMC3Analysis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named analysis

# Build rule for target.
analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analysis
.PHONY : analysis

# fast build rule for target.
analysis/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/analysis.dir/build.make src/CMakeFiles/analysis.dir/build
.PHONY : analysis/fast

#=============================================================================
# Target rules for targets named analyze_hepmc

# Build rule for target.
analyze_hepmc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analyze_hepmc
.PHONY : analyze_hepmc

# fast build rule for target.
analyze_hepmc/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/analyze_hepmc.dir/build.make src/CMakeFiles/analyze_hepmc.dir/build
.PHONY : analyze_hepmc/fast

#=============================================================================
# Target rules for targets named analyze_hepmcCC

# Build rule for target.
analyze_hepmcCC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analyze_hepmcCC
.PHONY : analyze_hepmcCC

# fast build rule for target.
analyze_hepmcCC/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/analyze_hepmcCC.dir/build.make src/CMakeFiles/analyze_hepmcCC.dir/build
.PHONY : analyze_hepmcCC/fast

#=============================================================================
# Target rules for targets named analyze_hepmcNC

# Build rule for target.
analyze_hepmcNC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analyze_hepmcNC
.PHONY : analyze_hepmcNC

# fast build rule for target.
analyze_hepmcNC/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/analyze_hepmcNC.dir/build.make src/CMakeFiles/analyze_hepmcNC.dir/build
.PHONY : analyze_hepmcNC/fast

#=============================================================================
# Target rules for targets named outgoing_particle_multiplicity

# Build rule for target.
outgoing_particle_multiplicity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 outgoing_particle_multiplicity
.PHONY : outgoing_particle_multiplicity

# fast build rule for target.
outgoing_particle_multiplicity/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/outgoing_particle_multiplicity.dir/build.make src/CMakeFiles/outgoing_particle_multiplicity.dir/build
.PHONY : outgoing_particle_multiplicity/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... analysis"
	@echo "... analyze_hepmc"
	@echo "... analyze_hepmcCC"
	@echo "... analyze_hepmcNC"
	@echo "... outgoing_particle_multiplicity"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

